'use client';
import { useEffect, useState } from 'react';
import { BarChart3, ExternalLink, Package, Settings, ShoppingBag, Plus, Pencil, Trash2, Save, LogOut } from 'lucide-react';
import { products as demoProducts } from '@/data/products';

type AdminProduct={id:string|number;name:string;slug?:string;price:number;mrp:number;rating:number;reviews:number|string;description?:string;image_url?:string;amazon_url?:string;flipkart_url?:string;featured?:boolean;active?:boolean;sort_order?:number};
const empty:AdminProduct={id:'new',name:'',slug:'',price:0,mrp:0,rating:0,reviews:0,description:'',image_url:'',amazon_url:'',flipkart_url:'',featured:true,active:true,sort_order:0};

export default function AdminPage(){
 const [tab,setTab]=useState('overview'); const [items,setItems]=useState<AdminProduct[]>(demoProducts as AdminProduct[]); const [editing,setEditing]=useState<AdminProduct|null>(null); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [connected,setConnected]=useState(false);
 const load=async()=>{try{const r=await fetch('/api/admin/products',{cache:'no-store'});if(!r.ok) return;const j=await r.json();setItems(j.products ?? []);setConnected(true)}catch{}}
 useEffect(()=>{load()},[]);
 const save=async()=>{if(!editing?.name.trim()) return setMessage('Product name is required.');setLoading(true);setMessage('');const isNew=editing.id==='new';const url=isNew?'/api/admin/products':`/api/admin/products/${editing.id}`;const r=await fetch(url,{method:isNew?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});const j=await r.json();setLoading(false);if(!r.ok)return setMessage(j.error||'Could not save product.');setEditing(null);setMessage('Saved successfully.');load()}
 const remove=async(id:string|number)=>{if(!confirm('Delete this product?'))return;const r=await fetch(`/api/admin/products/${id}`,{method:'DELETE'});if(r.ok){setMessage('Product deleted.');load()}else{const j=await r.json();setMessage(j.error||'Delete failed.')}}
 const logout=async()=>{await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'};
 return <div className="admin-shell"><aside><div className="admin-logo">LOLA <small>OWNER</small></div><button onClick={()=>setTab('overview')} className={tab==='overview'?'active':''}><BarChart3/> Overview</button><button onClick={()=>setTab('products')} className={tab==='products'?'active':''}><Package/> Products</button><button onClick={()=>setTab('marketplaces')} className={tab==='marketplaces'?'active':''}><ShoppingBag/> Marketplaces</button><button onClick={()=>setTab('settings')} className={tab==='settings'?'active':''}><Settings/> Store settings</button><a href="/"><ExternalLink/> View store</a><button onClick={logout}><LogOut/> Logout</button></aside><section className="admin-main"><div className="admin-top"><div><p className="eyebrow">PRIVATE OWNER AREA</p><h1>{tab==='overview'?'Good evening.':tab==='products'?'Products':tab==='marketplaces'?'Marketplace links':'Store settings'}</h1></div><span className="secure">{connected?'DATABASE CONNECTED':'DEMO MODE'}</span></div>{message&&<div className="admin-message">{message}</div>}
 {tab==='overview'&&<><div className="stats"><div><span>Products</span><strong>{String(items.length).padStart(2,'0')}</strong></div><div><span>Live listings</span><strong>{String(items.filter(x=>x.active!==false).length).padStart(2,'0')}</strong></div><div><span>Amazon links</span><strong>{String(items.filter(x=>x.amazon_url).length).padStart(2,'0')}</strong></div><div><span>Flipkart links</span><strong>{String(items.filter(x=>x.flipkart_url).length).padStart(2,'0')}</strong></div></div><div className="admin-card"><h2>Quick actions</h2><p>Add products, update pricing, images, descriptions, or marketplace links.</p><button className="admin-btn" onClick={()=>setTab('products')}>Manage products →</button></div></>}
 {tab==='products'&&<><div className="admin-card"><div className="admin-row"><div><h2>Product catalogue</h2><p>Changes save to Supabase when the project environment is connected.</p></div><button className="admin-btn" onClick={()=>setEditing({...empty,id:'new'})}><Plus/> Add product</button></div>{items.map(p=><div className="product-row" key={String(p.id)}><span><b>{p.name}</b><small>{p.active===false?'Hidden':'Live'}</small></span><b>₹{p.price}</b><div><button onClick={()=>setEditing({...p})} aria-label={`Edit ${p.name}`}><Pencil/></button>{p.id!=='new'&&<button onClick={()=>remove(p.id)} aria-label={`Delete ${p.name}`}><Trash2/></button>}</div></div>)}</div>{editing&&<div className="admin-card"><div className="admin-row"><h2>{editing.id==='new'?'Add product':'Edit product'}</h2><button className="admin-btn" onClick={save} disabled={loading}><Save/> {loading?'Saving…':'Save product'}</button></div><div className="admin-form-grid"><label>Product name<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Slug<input value={editing.slug||''} onChange={e=>setEditing({...editing,slug:e.target.value})}/></label><label>Price<input type="number" value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><label>MRP<input type="number" value={editing.mrp} onChange={e=>setEditing({...editing,mrp:Number(e.target.value)})}/></label><label>Rating<input type="number" step="0.1" min="0" max="5" value={editing.rating} onChange={e=>setEditing({...editing,rating:Number(e.target.value)})}/></label><label>Reviews<input type="number" value={editing.reviews} onChange={e=>setEditing({...editing,reviews:Number(e.target.value)})}/></label><label>Image URL<input value={editing.image_url||''} onChange={e=>setEditing({...editing,image_url:e.target.value})} placeholder="Supabase/public image URL"/></label><label>Sort order<input type="number" value={editing.sort_order||0} onChange={e=>setEditing({...editing,sort_order:Number(e.target.value)})}/></label><label className="wide">Description<input value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Amazon URL<input value={editing.amazon_url||''} onChange={e=>setEditing({...editing,amazon_url:e.target.value})}/></label><label>Flipkart URL<input value={editing.flipkart_url||''} onChange={e=>setEditing({...editing,flipkart_url:e.target.value})}/></label></div></div></>}
 {tab==='marketplaces'&&<div className="admin-card"><h2>Marketplace connections</h2><p>Official product links can now be stored per product in the Products editor.</p><button className="admin-btn" onClick={()=>setTab('products')}>Open product links →</button></div>}
 {tab==='settings'&&<div className="admin-card"><h2>Brand settings</h2><p>Global brand settings are the next database-backed step. Product management is already wired to the admin API.</p><button className="admin-btn" onClick={()=>setTab('products')}>Manage catalogue →</button></div>}
 </section></div>
}
