import { ArrowRight, Heart, Sparkles, Zap, Truck, ShieldCheck, Leaf } from 'lucide-react';
import { ProductCard } from '@/components/product-card';
import { products } from '@/data/products';

export default function Home(){
 return <div id="top">
  <section className="hero"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">LOLA ENGLAND · WOMEN’S EDIT</p><h1>Wear your<br/><em>mood.</em></h1><p className="hero-text">Elegant everyday T-shirts with a soft, feminine identity. Designed to feel effortless, look elevated, and live beautifully in your everyday wardrobe.</p><a className="btn btn-dark" href="#shop">SHOP T-SHIRTS <ArrowRight/></a><div className="hero-benefits"><span><Truck/>Free shipping<small>On orders over ₹799</small></span><span><ShieldCheck/>Premium quality<small>Everyday comfort</small></span><span><Heart/>Made for women<small>Designed to express</small></span><span><Leaf/>Thoughtful choices<small>Easy everyday style</small></span></div></div><div className="hero-visual"><img src="/models/model-hero.svg" alt="LOLA ENGLAND fashion model wearing a branded T-shirt"/><div className="hero-stamp">MORE<br/><i>than</i><br/>JUST A TEE ♡</div><div className="hero-note">NEW SEASON<br/><strong>ESSENTIALS</strong></div></div></div></section>

  <section className="lookbook section" id="models"><div className="container"><div className="section-head"><div><p className="eyebrow">THE LOLA LOOKBOOK</p><h2>Styled on her.</h2><p>AI-inspired fashion model looks for the latest LOLA mood.</p></div><a className="arrow-link" href="#shop">Shop the looks →</a></div><div className="model-grid"><article className="model-card model-tall"><img src="/models/model-pink.svg" alt="AI-inspired LOLA fashion model in pink T-shirt"/><div><span>01 · SOFT PINK</span><h3>Pretty, playful, effortless.</h3><a href="#shop">Explore pink edit →</a></div></article><article className="model-card"><img src="/models/model-black.svg" alt="AI-inspired LOLA fashion model in black T-shirt"/><div><span>02 · AFTER DARK</span><h3>Bold looks, easy fit.</h3><a href="#shop">Explore black edit →</a></div></article><article className="model-card model-message"><div><span>LOLA ENGLAND</span><h3>Be you.<br/><i>Be LOLA.</i></h3><p>#LOLAENGLAND</p><a href="#shop" className="btn btn-light">SHOP T-SHIRTS</a></div></article></div></div></section>

  <section className="section" id="shop"><div className="container"><div className="section-head"><div><h2>Trending now</h2><p>Curated women’s T-shirts</p></div><a className="arrow-link" href="#shop">View all →</a></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>

  <section className="section features" id="about"><div className="container feature-grid"><div className="feature-card"><Sparkles/><h3>Marketplace ready</h3><p>Connect approved Amazon, Flipkart and other marketplace links product-by-product.</p></div><div className="feature-card"><Heart/><h3>Made for mobile</h3><p>Built around social traffic from Instagram, WhatsApp and short-form content.</p></div><div className="feature-card"><Zap/><h3>Easy to manage</h3><p>Owner tools are designed so products, prices and marketplace links can change without editing code.</p></div></div></section>

  <section className="container join"><div><p className="eyebrow">JOIN THE LOLA LIST</p><h2>First look.<br/>First picks.</h2><p>Get new drops, limited edits and early access in your inbox.</p><form><input type="email" placeholder="Your email address" aria-label="Your email address"/><button className="btn btn-light" type="submit">JOIN</button></form></div></section>

  <section className="section faq" id="faq"><div className="container"><div className="section-head"><div><p className="eyebrow">NEED TO KNOW</p><h2>Questions, answered.</h2></div></div><details><summary>Where can I buy LOLA ENGLAND?</summary><p>Products will be available through approved marketplace listings. Amazon and Flipkart links can be added product-by-product from the owner dashboard.</p></details><details><summary>Do you offer women’s oversized T-shirts?</summary><p>Yes. Oversized, graphic and everyday women’s T-shirts are part of the current collection.</p></details><details><summary>Can prices change?</summary><p>Yes. Product pricing is designed to be managed from the private owner dashboard.</p></details></div></section>
 </div>
}
