'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {CheckCircle2,PackageSearch,Truck,Clock3,ArrowLeft} from 'lucide-react';

const steps=[['awaiting_payment','Payment'],['payment_submitted','Payment received'],['paid','Paid'],['confirmed','Confirmed'],['shipped','Shipped'],['delivered','Delivered']];
function rank(status:string){if(status==='cancelled'||status==='cod_pending')return -1;const i=steps.findIndex(([s])=>s===status);return i<0?0:i;}
function label(status:string){return status==='cod_pending'?'COD order confirmed':status.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());}
export default function TrackOrder(){
 const [order,setOrder]=useState('');const [phone,setPhone]=useState('');const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setData(null);setBusy(true);try{const r=await fetch(`/api/orders/track?order=${encodeURIComponent(order.trim())}&phone=${encodeURIComponent(phone)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Order not found.');setData(d.order);}catch(e){setError(e instanceof Error?e.message:'Unable to track order.');}finally{setBusy(false);}};
 const current=rank(data?.status||'');
 return <main className="checkout-page"><div className="container" style={{maxWidth:900}}><Link className="back-link" href="/"><ArrowLeft/> Back to LOLA</Link><section className="checkout-card" style={{marginTop:30}}><p className="editorial-eyebrow">ORDER TRACKING</p><h1>Where is your <br/><em>LOLA order?</em></h1><p style={{color:'#777',maxWidth:620,lineHeight:1.7}}>Enter the order ID and phone number used at checkout. You can check the latest order status without creating an account.</p><form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:28}}><label style={{fontSize:12,fontWeight:800}}>Order ID<input value={order} onChange={e=>setOrder(e.target.value)} placeholder="Paste your order ID" required style={{display:'block',width:'100%',marginTop:7,border:'1px solid var(--line)',borderRadius:14,padding:15}}/></label><label style={{fontSize:12,fontWeight:800}}>Phone number<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="tel" placeholder="10-digit mobile number" required style={{display:'block',width:'100%',marginTop:7,border:'1px solid var(--line)',borderRadius:14,padding:15}}/></label><button className="checkout-pay" disabled={busy} style={{gridColumn:'1/-1'}}>{busy?'Checking order…':'Track order'}</button></form>{error&&<div className="checkout-error">{error}</div>}
 {data&&<div style={{marginTop:35,borderTop:'1px solid var(--line)',paddingTop:30}}><div style={{display:'flex',justifyContent:'space-between',gap:15,flexWrap:'wrap'}}><div><p className="editorial-eyebrow">ORDER</p><strong style={{fontSize:14}}>{data.id}</strong></div><div style={{textAlign:'right'}}><p className="editorial-eyebrow">STATUS</p><strong>{label(data.status)}</strong></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:8,marginTop:30}}>{steps.map(([s,name],i)=><div key={s} style={{textAlign:'center',opacity:i<=current?.valueOf()?1:.35}}><div style={{width:34,height:34,borderRadius:'50%',margin:'0 auto 8px',display:'grid',placeItems:'center',background:i<=current?'#111':'#eee',color:i<=current?'#fff':'#777'}}>{i<=current?<CheckCircle2 size={17}/>:<Clock3 size={16}/>}</div><small style={{fontSize:10,fontWeight:700}}>{name}</small></div>)}</div><div style={{display:'grid',gap:12,marginTop:30}}>{(data.items||[]).map((item:any)=><div key={`${item.id}-${item.size}`} style={{display:'flex',justifyContent:'space-between',gap:15,padding:'12px 0',borderBottom:'1px solid var(--line)'}}><span><strong>{item.name}</strong><br/><small style={{color:'#888'}}>Size {item.size} · Qty {item.quantity}</small></span><strong>₹{Number(item.price*item.quantity).toLocaleString('en-IN')}</strong></div>)}</div><div style={{display:'flex',justifyContent:'space-between',marginTop:18,fontSize:18}}><strong>Total</strong><strong>₹{data.totalAmount.toLocaleString('en-IN')}</strong></div></div>}
 </section></div></main>;
}
