'use client';

import Link from 'next/link';
import { ArrowUpRight, Check, X } from 'lucide-react';
import { useEffect } from 'react';
import { SafeImage } from '@/components/safe-image';
import type { Product } from '@/components/product-card';

export function ProductQuickView({product,onClose}:{product:Product;onClose:()=>void}){
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();document.addEventListener('keydown',onKey);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=''}},[onClose]);
 const image=product.image_url||'/products/lola-mint-front.webp?v=6';
 return <div role="dialog" aria-modal="true" aria-label={'Quick view: '+product.name} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}} style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.62)',display:'grid',placeItems:'center',padding:16}}><div style={{position:'relative',width:'min(920px,100%)',maxHeight:'92vh',overflow:'auto',background:'#fff',borderRadius:22,display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',boxShadow:'0 24px 80px rgba(0,0,0,.28)'}}><button onClick={onClose} aria-label="Close quick view" style={{position:'absolute',right:14,top:14,zIndex:2,width:42,height:42,border:0,borderRadius:'50%',background:'#fff',boxShadow:'0 4px 16px rgba(0,0,0,.12)',display:'grid',placeItems:'center',cursor:'pointer'}}><X/></button><div style={{background:'#f4f1ec',minHeight:420}}><SafeImage src={image} fallbackSrc={image} alt={product.name+' product preview'} width={900} height={1050} style={{width:'100%',height:'100%',objectFit:'cover'}}/></div><div style={{padding:'clamp(24px,5vw,52px)',display:'flex',flexDirection:'column',justifyContent:'center',gap:14}}><p style={{fontSize:11,letterSpacing:'.18em',fontWeight:700,margin:0}}>LOLA ENGLAND</p><h2 style={{fontSize:'clamp(26px,4vw,42px)',lineHeight:1.05,margin:0}}>{product.name}</h2><div style={{fontSize:20,fontWeight:700}}>₹{product.price.toLocaleString('en-IN')} <del style={{fontSize:14,fontWeight:400,opacity:.5}}>₹{product.mrp.toLocaleString('en-IN')}</del></div><div style={{fontSize:14}}>★ {product.rating} · {Number(product.reviews||0).toLocaleString('en-IN')} reviews</div><p style={{lineHeight:1.65,margin:'4px 0'}}>{product.description||'A statement everyday tee designed for effortless styling.'}</p>{product.fabric?<p style={{margin:0}}><strong>Fabric:</strong> {product.fabric}</p>:null}<div style={{display:'flex',gap:8,alignItems:'center',fontSize:12,padding:'11px 12px',background:'#f6f6f3',borderRadius:10}}><Check size={16}/> Open the full product page for size, stock and checkout.</div><div style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:6}}><Link href={'/product/'+encodeURIComponent(String(product.id))} onClick={onClose} style={{display:'inline-flex',alignItems:'center',gap:8,padding:'13px 18px',background:'#111',color:'#fff',borderRadius:999,textDecoration:'none',fontWeight:700}}>View product <ArrowUpRight size={16}/></Link><button onClick={onClose} style={{padding:'13px 18px',border:'1px solid #ddd',background:'#fff',borderRadius:999,cursor:'pointer'}}>Keep browsing</button></div></div></div></div>;
}
