'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import QRCode from 'qrcode';
import {ArrowLeft,CheckCircle2,ShieldCheck,Truck,WalletCards,Copy,ExternalLink} from 'lucide-react';
import {useCart} from '@/components/cart-provider';

type Payment={orderRecordId:string;upiUri:string;upiId:string;upiName:string;transactionNote:string;subtotal:number;shippingFee:number;platformFee:number;gstRate:number;gstAmount:number;totalAmount:number;qr:string};
export default function CheckoutPage(){
 const {items,total,clear}=useCart(); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
 const [customer,setCustomer]=useState({name:'',phone:'',email:'',address:''}); const [payment,setPayment]=useState<Payment|null>(null);
 const update=(k:string,v:string)=>setCustomer(c=>({...c,[k]:v})); const totalText=useMemo(()=>total.toLocaleString('en-IN'),[total]);
 async function startPayment(){
  setError(''); if(!items.length)return setError('Your bag is empty.');
  if(!customer.name||!customer.phone||!customer.address)return setError('Please enter your name, phone and delivery address.');
  setBusy(true);
  try{const res=await fetch('/api/payment/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,customer})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to create payment.');const qr=await QRCode.toDataURL(data.upiUri,{width:420,margin:2,errorCorrectionLevel:'M'});setPayment({...data,qr});}
  catch(e){setError(e instanceof Error?e.message:'Payment could not start.');}finally{setBusy(false);}
 }
 async function confirmPayment(){if(!payment)return;setBusy(true);try{const res=await fetch('/api/payment/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderRecordId:payment.orderRecordId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not submit order.');clear();setDone(true);}catch(e){setError(e instanceof Error?e.message:'Could not submit order.');}finally{setBusy(false);}}\n async function copy(text:string){try{await navigator.clipboard.writeText(text);}catch{}}
 if(done)return <main className="checkout-page"><div className="checkout-success"><CheckCircle2 size={64}/><p className="editorial-eyebrow">ORDER RECEIVED</p><h1>Thank you, <br/><em>LOLA girl.</em></h1><p>Your QR payment order has been created. Once the payment is received and confirmed in the owner dashboard, your order can be processed.</p><Link className="btn btn-dark" href="/">Continue shopping</Link></div></main>;
 return <main className="checkout-page"><div className="container checkout-wrap"><Link className="back-link" href="/cart"><ArrowLeft/> Back to bag</Link>
 <div className="checkout-grid"><section className="checkout-card"><p className="editorial-eyebrow">SECURE UPI CHECKOUT</p><h1>Pay your way.<br/><em>Scan & go.</em></h1><div className="trust-row"><span><ShieldCheck/> Secure order</span><span><Truck/> Fast delivery</span><span><WalletCards/> UPI QR</span></div>
 {!payment?<div className="checkout-form"><label>Full name<input value={customer.name} onChange={e=>update('name',e.target.value)} placeholder="Your name"/></label><label>Phone number<input inputMode="tel" value={customer.phone} onChange={e=>update('phone',e.target.value)} placeholder="+91"/></label><label>Email <span>(optional)</span><input type="email" value={customer.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com"/></label><label>Delivery address<textarea value={customer.address} onChange={e=>update('address',e.target.value)} placeholder="House / flat, street, city, state, PIN"/></label></div>:null}
 {payment?<div className="upi-payment-box"><div className="upi-amount">Pay <strong>₹{payment.totalAmount.toLocaleString('en-IN')}</strong></div><p className="upi-caption">Scan with Google Pay, PhonePe, Paytm, BHIM or any UPI app.</p><img className="upi-qr" src={payment.qr} alt="LOLA ENGLAND UPI payment QR code"/><div className="upi-id-row"><span>UPI ID</span><strong>{payment.upiId}</strong><button type="button" onClick={()=>copy(payment.upiId)} aria-label="Copy UPI ID"><Copy size={16}/></button></div><button type="button" className="upi-open-btn" onClick={()=>{window.location.href=payment.upiUri}}><ExternalLink size={17}/> Open UPI app</button><p className="upi-note">Payment note: <strong>{payment.transactionNote}</strong></p><div className="checkout-charge-mini"><span>Subtotal <b>₹{payment.subtotal.toLocaleString('en-IN')}</b></span><span>Shipping <b>{payment.shippingFee?'₹'+payment.shippingFee.toLocaleString('en-IN'):'FREE'}</b></span><span>Platform fee <b>₹{payment.platformFee.toLocaleString('en-IN')}</b></span><span>GST ({payment.gstRate}%) <b>₹{payment.gstAmount.toLocaleString('en-IN')}</b></span><strong>Total <b>₹{payment.totalAmount.toLocaleString('en-IN')}</b></strong></div><button type="button" className="checkout-pay" onClick={confirmPayment} disabled={busy}>{busy?'Submitting order…':'I’ve completed the payment'}</button><p className="upi-note">Payment status is confirmed by the owner from the payment account/bank records. You do not need to enter a UTR.</p><button type="button" className="change-payment" onClick={()=>setPayment(null)}>← Change details</button></div>:<button className="checkout-pay" onClick={startPayment} disabled={busy||!items.length}>{busy?'Creating secure QR…':'Continue to UPI QR · ₹'+totalText}</button>}
 {error&&<div className="checkout-error">{error}</div>}<p className="checkout-note">Never share your UPI PIN or OTP with anyone.</p></section>
 <aside className="checkout-summary"><p className="editorial-eyebrow">YOUR LOLA BAG</p>{items.map(i=><div className="checkout-item" key={i.lineId}><img src={i.image} alt=""/><div><b>{i.name}</b><span>Size {i.size} · Qty {i.quantity}</span></div><strong>₹{(i.price*i.quantity).toLocaleString('en-IN')}</strong></div>)}<div className="checkout-total"><span>Subtotal</span><b>₹{totalText}</b></div><small className="checkout-note">Final shipping, platform fee and GST are calculated before the QR is created.</small></aside></div></div></main>;
}
