'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Script from 'next/script';
import QRCode from 'qrcode';
import {ArrowLeft,CheckCircle2,ShieldCheck,Truck,WalletCards,Copy,ExternalLink,CreditCard,Banknote,MapPin,Loader2} from 'lucide-react';
import {useCart} from '@/components/cart-provider';
import {trackAddPaymentInfo,trackBeginCheckout,trackPurchase} from '@/lib/analytics';

type Method='upi'|'card'|'cod';
type Config={upiEnabled:boolean;upiId:string;upiName:string;cardEnabled:boolean;codEnabled:boolean;codFee:number};
type PinState={loading:boolean;checked:boolean;serviceable:boolean;message:string;city?:string;state?:string};
type Payment={orderRecordId:string;upiUri?:string;upiId?:string;upiName?:string;transactionNote?:string;subtotal:number;shippingFee:number;platformFee:number;gstRate:number;gstAmount:number;totalAmount:number;discountAmount:number;couponCode:string;qr?:string;razorpayOrderId?:string;keyId?:string;method:Method;codFee?:number};

export default function CheckoutPage(){
 const {items,total,clear}=useCart();
 const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState(''); const [doneMethod,setDoneMethod]=useState<Method>('upi');
 const [config,setConfig]=useState<Config>({upiEnabled:false,upiId:'',upiName:'LOLA ENGLAND',cardEnabled:false,codEnabled:false,codFee:0});
 const [method,setMethod]=useState<Method>('upi');
 const [customer,setCustomer]=useState({name:'',phone:'',email:'',address:'',pincode:''});
 const [pin,setPin]=useState<PinState>({loading:false,checked:false,serviceable:false,message:''});
 const [couponCode,setCouponCode]=useState(''); const [payment,setPayment]=useState<Payment|null>(null); const [showQr,setShowQr]=useState(false);
 useEffect(()=>{fetch('/api/payment/config',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d&&typeof d==='object'){setConfig(d);if(d.upiEnabled)setMethod('upi');else if(d.cardEnabled)setMethod('card');else if(d.codEnabled)setMethod('cod');}}).catch(()=>{});},[]);
 useEffect(()=>{if(!items.length)return;trackBeginCheckout(items.map(i=>({item_id:i.id,item_name:i.name,price:i.price,quantity:i.quantity,item_variant:i.color?`${i.color} / ${i.size}`:i.size})),total);},[items.length]);
 const update=(k:string,v:string)=>setCustomer(c=>({...c,[k]:v}));
 const totalText=useMemo(()=>total.toLocaleString('en-IN'),[total]);
 const verifyPincode=async()=>{const value=customer.pincode.replace(/\D/g,'').slice(0,6);update('pincode',value);if(value.length!==6){setPin({loading:false,checked:false,serviceable:false,message:'Enter a 6-digit pincode.'});return;}setPin({loading:true,checked:false,serviceable:false,message:'Checking delivery availability…'});try{const r=await fetch(`/api/shipping/pincode?pincode=${value}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Pincode could not be verified.');setPin({loading:false,checked:true,serviceable:true,message:d.message,city:d.city,state:d.state});}catch(e){setPin({loading:false,checked:true,serviceable:false,message:e instanceof Error?e.message:'Could not verify this pincode.'});}};
 const start=async()=>{setError('');if(!items.length)return setError('Your bag is empty.');if(!customer.name||!customer.phone||!customer.address||!customer.pincode)return setError('Please enter your name, phone, delivery address and pincode.');if(!pin.checked||!pin.serviceable)return setError('Please verify your delivery pincode before continuing.');if(method==='upi'&&!config.upiEnabled)return setError('UPI payments are currently unavailable.');if(method==='card'&&!config.cardEnabled)return setError('Card payments are currently unavailable.');if(method==='cod'&&!config.codEnabled)return setError('Cash on Delivery is currently unavailable.');setBusy(true);try{const res=await fetch('/api/payment/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,customer,couponCode,method})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to create order.');const analyticsItems=items.map(i=>({item_id:i.id,item_name:i.name,price:i.price,quantity:i.quantity,item_variant:i.color?`${i.color} / ${i.size}`:i.size}));trackAddPaymentInfo(analyticsItems,Number(data.totalAmount||total),method);
 if(method==='cod'){clear();setDoneMethod('cod');setDone(true);trackPurchase(data.orderRecordId,analyticsItems,Number(data.totalAmount||total),'cod');return;}if(method==='upi'){const qr=await QRCode.toDataURL(data.upiUri,{width:420,margin:2,errorCorrectionLevel:'M'});setPayment({...data,qr,method});setShowQr(false);setTimeout(()=>{try{window.location.href=data.upiUri;}catch{}},120);return;}if(!(window as any).Razorpay)throw new Error('Secure card checkout is still loading. Please try again.');const rzp=new (window as any).Razorpay({key:data.keyId,amount:Math.round(data.totalAmount*100),currency:'INR',name:'LOLA ENGLAND',description:'LOLA ENGLAND order',order_id:data.razorpayOrderId,prefill:{name:customer.name,email:customer.email,contact:customer.phone},theme:{color:'#111111'},handler:async(response:any)=>{setBusy(true);try{const vr=await fetch('/api/payment/razorpay/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderRecordId:data.orderRecordId,razorpay_payment_id:response.razorpay_payment_id,razorpay_order_id:response.razorpay_order_id,razorpay_signature:response.razorpay_signature})});const vd=await vr.json();if(!vr.ok)throw new Error(vd.error||'Payment verification failed.');clear();setDoneMethod('card');setDone(true);trackPurchase(data.orderRecordId,analyticsItems,Number(data.totalAmount||total),'card');}catch(e){setError(e instanceof Error?e.message:'Payment verification failed.');}finally{setBusy(false);}},modal:{ondismiss:()=>setBusy(false)}});rzp.on('payment.failed',(response:any)=>setError(response?.error?.description||'Card payment failed. Please try again.'));rzp.open();}catch(e){setError(e instanceof Error?e.message:'Payment could not start.');}finally{if(method!=='card')setBusy(false);}};
 async function copy(text:string){try{await navigator.clipboard.writeText(text);}catch{}}
 if(done)return <main className="checkout-page"><div className="checkout-success"><CheckCircle2 size={64}/><p className="editorial-eyebrow">{doneMethod==='cod'?'ORDER CONFIRMED':'ORDER RECEIVED'}</p><h1>Thank you, <br/><em>LOLA girl.</em></h1><p>{doneMethod==='cod'?'Your Cash on Delivery order has been placed. We will contact you before dispatch.':doneMethod==='card'?'Your card payment has been submitted and your order is being confirmed.':'Your UPI order has been received. Once the payment is confirmed, your order can be processed.'}</p><div className="checkout-success-actions"><Link className="btn btn-dark" href="/">Continue shopping</Link><Link className="btn btn-light" href="/returns">Returns & refunds</Link></div></div></main>;
 return <main className="checkout-page"><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><div className="container checkout-wrap"><Link className="back-link" href="/cart"><ArrowLeft/> Back to bag</Link><div className="checkout-grid"><section className="checkout-card"><p className="editorial-eyebrow">SECURE CHECKOUT</p><h1>Pay your way.<br/><em>Choose what suits you.</em></h1><div className="trust-row"><span><ShieldCheck/> Secure order</span><span><Truck/> Fast delivery</span><span><WalletCards/> Multiple payment options</span></div>
 {!payment?<><div className="payment-method-grid">{config.upiEnabled&&<button type="button" className={'payment-method-option '+(method==='upi'?'active':'')} onClick={()=>setMethod('upi')}><span className="payment-app-icons"><span className="payment-app-logo gpay"><span>G</span></span><span className="payment-app-logo phonepe"><span>पे</span></span><span className="payment-app-logo paytm"><span>paytm</span></span><span className="payment-app-logo bhim"><span>BHIM</span></span></span><span><b>UPI</b><small>Google Pay · PhonePe · Paytm · BHIM</small></span></button>}{config.cardEnabled&&<button type="button" className={'payment-method-option '+(method==='card'?'active':'')} onClick={()=>setMethod('card')}><span className="payment-app-icons"><span className="payment-app-logo card-logo">▱</span></span><span><b>Credit / Debit Card</b><small>Visa · Mastercard · RuPay · Razorpay</small></span></button>}{config.codEnabled&&<button type="button" className={'payment-method-option '+(method==='cod'?'active':'')} onClick={()=>setMethod('cod')}><span className="payment-app-icons"><span className="payment-app-logo cod-logo">₹</span></span><span><b>Cash on Delivery</b><small>{config.codFee?'₹'+config.codFee+' COD fee':'Pay when delivered'}</small></span></button>}</div>
 <div className="checkout-form"><label>Full name<input value={customer.name} onChange={e=>update('name',e.target.value)} placeholder="Your name"/></label><label>Phone number<input inputMode="tel" value={customer.phone} onChange={e=>update('phone',e.target.value)} placeholder="+91"/></label><label>Email <span>(optional)</span><input type="email" value={customer.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com"/></label><label>Coupon code <span>(optional)</span><input value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())} placeholder="e.g. LOLA10"/></label><label>Delivery address<textarea value={customer.address} onChange={e=>update('address',e.target.value)} placeholder="House / flat, street, area, city, state"/></label><div className="pincode-field"><label>Delivery pincode<input inputMode="numeric" maxLength={6} value={customer.pincode} onChange={e=>{update('pincode',e.target.value.replace(/\D/g,'').slice(0,6));setPin(p=>({...p,checked:false,message:''}));}} onBlur={verifyPincode} placeholder="6-digit PIN code"/></label><button type="button" className="pincode-check" onClick={verifyPincode} disabled={pin.loading||customer.pincode.length!==6}>{pin.loading?<Loader2 size={16} className="spin"/>:<MapPin size={16}/>} {pin.loading?'Checking…':'Check delivery'}</button></div>{pin.message&&<div className={'pincode-result '+(pin.serviceable?'success':'error')}>{pin.serviceable?<><CheckCircle2 size={16}/><span>{pin.message}{pin.city&&pin.state?<><br/><strong>{pin.city}, {pin.state}</strong></>:null}</span></>:<span>{pin.message}</span>}</div>}</div>
 <button className="checkout-pay" onClick={start} disabled={busy||!items.length}>{busy?'Opening secure checkout…':method==='upi'?'Continue to Pay · ₹'+totalText:method==='card'?'Continue to Pay · ₹'+totalText:'Place COD Order · ₹'+totalText}</button></>:<div className="upi-payment-box"><div className="upi-payment-layout"><div className="upi-payment-copy"><div className="upi-amount">Pay <strong>₹{payment.totalAmount.toLocaleString('en-IN')}</strong></div><p className="upi-caption">We’ll open your preferred UPI app automatically. If it doesn’t open, use your UPI ID or reveal the QR.</p><div className="upi-id-row"><span>UPI ID</span><strong>{payment.upiId}</strong><button type="button" onClick={()=>copy(payment.upiId||'')} aria-label="Copy UPI ID"><Copy size={16}/></button></div><button type="button" className="upi-open-btn" onClick={()=>{window.location.href=payment.upiUri||''}}><ExternalLink size={17}/> Open UPI app</button><p className="upi-note">Payment note: <strong>{payment.transactionNote}</strong></p></div><div className={'upi-qr-reveal '+(showQr?'revealed':'')}><button type="button" className="upi-qr-image-button" onClick={()=>setShowQr(v=>!v)} aria-label="Enlarge QR code">{payment.qr&&<img className="upi-qr" src={payment.qr} alt="UPI payment QR code"/>}</button><span>Scan with any UPI app</span></div></div><div className="checkout-charge-mini"><h3>Payment breakdown</h3><span>Subtotal <b>₹{payment.subtotal.toLocaleString('en-IN')}</b></span><span>Shipping <b>{payment.shippingFee?'₹'+payment.shippingFee.toLocaleString('en-IN'):'FREE'}</b></span><span>Discount {payment.couponCode?<b>{'-₹'+payment.discountAmount.toLocaleString('en-IN')+' ('+payment.couponCode+')'}</b>:<b>₹0</b>}</span><span>Platform fee <b>₹{payment.platformFee.toLocaleString('en-IN')}</b></span><span>GST ({payment.gstRate}%) <b>₹{payment.gstAmount.toLocaleString('en-IN')}</b></span><strong>Total <b>₹{payment.totalAmount.toLocaleString('en-IN')}</b></strong></div><div className="upi-payment-status"><CheckCircle2 size={18}/><span>After paying, keep this order screen available while the payment is being verified.</span></div><button type="button" className="change-payment" onClick={()=>setPayment(null)}>← Change payment method</button></div>}{error&&<div className="checkout-error">{error}</div>}<p className="checkout-note">Never share your UPI PIN, card CVV or OTP with anyone.</p></section><aside className="checkout-summary"><p className="editorial-eyebrow">YOUR LOLA BAG</p>{items.map(i=><div className="checkout-item" key={i.lineId}><img src={i.image} alt=""/><div><b>{i.name}</b><span>Size {i.size} · Qty {i.quantity}</span></div><strong>₹{(i.price*i.quantity).toLocaleString('en-IN')}</strong></div>)}<div className="checkout-total"><span>Subtotal</span><b>₹{totalText}</b></div><small className="checkout-note">Final shipping, platform fee, GST and any COD fee are calculated securely before order creation.</small></aside></div></div></main>;
}
