'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';

type Review={id:string;product_id:string;rating:number;title:string|null;body:string;photos:string[];verified_purchase:boolean;status:string;created_at:string;products?:{name?:string}|null};

export default function AdminReviews(){
 const [reviews,setReviews]=useState<Review[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState('');
 async function load(){setLoading(true);const r=await fetch('/api/admin/reviews',{cache:'no-store'});const j=await r.json();if(!r.ok){setError(j.error||'Unable to load reviews');setLoading(false);return}setReviews(j.reviews||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function moderate(id:string,status:string){setBusy(id);setError('');const r=await fetch('/api/admin/reviews',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const j=await r.json();if(!r.ok)setError(j.error||'Update failed');else setReviews(x=>x.map(v=>v.id===id?{...v,status}:v));setBusy(null)}
 return <main style={{minHeight:'100vh',background:'#f6f4ef',padding:'28px',color:'#111'}}><div style={{maxWidth:1100,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:24}}><div><Link href="/admin" style={{fontSize:13,color:'#666'}}>← Admin dashboard</Link><h1 style={{fontFamily:'serif',fontSize:36,margin:'8px 0 4px'}}>Review Moderation</h1><p style={{margin:0,color:'#777'}}>Approve genuine customer reviews before they appear publicly.</p></div><button onClick={load} style={{border:'1px solid #ddd',background:'#fff',padding:'10px 15px',borderRadius:10}}>Refresh</button></div>{error&&<div style={{padding:12,borderRadius:10,background:'#fff0f0',color:'#a33',marginBottom:16}}>{error}</div>}{loading?<p>Loading reviews…</p>:reviews.length===0?<div style={{background:'#fff',padding:28,borderRadius:16}}>No reviews yet.</div>:<div style={{display:'grid',gap:14}}>{reviews.map(r=><article key={r.id} style={{background:'#fff',border:'1px solid #e5e2db',borderRadius:16,padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><strong>{r.products?.name||'Product'}</strong><div style={{marginTop:5}}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)} {r.verified_purchase&&<span style={{color:'#28744b',fontSize:12,fontWeight:700}}> · Verified purchase</span>}</div></div><span style={{padding:'5px 9px',borderRadius:999,background:r.status==='approved'?'#e8f5ed':r.status==='rejected'?'#fdecec':'#fff4dc',fontSize:12,fontWeight:700}}>{r.status}</span></div>{r.title&&<h3 style={{margin:'14px 0 5px'}}>{r.title}</h3>}<p style={{color:'#555',lineHeight:1.55,whiteSpace:'pre-wrap'}}>{r.body}</p>{r.photos?.length>0&&<div style={{display:'flex',gap:8,overflow:'auto'}}>{r.photos.map((p,i)=><img key={i} src={p} alt="Customer review" style={{width:90,height:90,objectFit:'cover',borderRadius:10}}/>)}</div>}<div style={{display:'flex',gap:8,marginTop:16}}>{r.status!=='approved'&&<button disabled={busy===r.id} onClick={()=>moderate(r.id,'approved')} style={{background:'#111',color:'#fff',border:0,borderRadius:9,padding:'9px 14px'}}>{busy===r.id?'Saving…':'Approve'}</button>}{r.status!=='rejected'&&<button disabled={busy===r.id} onClick={()=>moderate(r.id,'rejected')} style={{background:'#fff',color:'#a33',border:'1px solid #e5bcbc',borderRadius:9,padding:'9px 14px'}}>Reject</button>}</div></article>)}</div>}</div></main>
}
